### ISSUE TITLE
导出的excel不对,生成.strings文件失败

### ISSUE THREAD

**Issue by Bluelich** [CatchZeng/Localizable.strings2Excel#1]
导出的excel只有一列key值
excel生成 **.strings文件失败

因为我的excel里面包含了多语言,每个语言为一列,格式如下:

keyName | en |  zh-Hans | zh-Hant | es 
----|-----|----|----|----
someKey | ...  | ... | ... | ...
...
...

是否可以支持:
1.生成多语言的excel
2.从多语言的excel导出为**.strings文件

**Comment by CatchZeng** [comment]
谢谢你的反馈和建议，我会尽快增加此功能

**Comment by CatchZeng** [comment]
@Bluelich  已在V0.4.0增加了多语言的功能

**Comment by Bluelich** [comment]
@CatchZeng Thank you! I will test this case later!
