### ISSUE TITLE
ModuleNotFoundError: No module named 'Workbook'

### ISSUE THREAD

**Issue by xuezou** [CatchZeng/Localizable.strings2Excel#12]
报错在这：
ACEdeMBP:python leopard$ python Localizable.py -f ../ios/ -t ../xls/
Traceback (most recent call last):
  File "Localizable.py", line 6, in <module>
    import pyExcelerator
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyExcelerator/__init__.py", line 12, in <module>
    from Workbook import Workbook
ModuleNotFoundError: No module named 'Workbook'

使用pip3 install Workbook下载了还是报错找不到Workbook。
ACEdeMBP:python leopard$ pip3 install Workbook
Requirement already satisfied: Workbook in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requirement already satisfied: xlutils in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Workbook)
Requirement already satisfied: xlwt in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from Workbook)
Requirement already satisfied: xlrd>=0.7.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from xlutils->Workbook)

没能从搜索引擎搜索到解决办法，求助。
这里是跟python版本相关么？我的是：
Python 3.6.3

**Comment by CatchZeng** [comment]
我没试过Python 3.6.3的，你切换到2.x试下

**Comment by xuezou** [comment]
是的，Python2.7没有问题，我一开始以为你的是Python3.

**Comment by CatchZeng** [comment]
没问题的话，我就先关闭了，有问题再联系
