### ISSUE TITLE
生成出来的文件是空的

### ISSUE THREAD

**Issue by huituzidd** [CatchZeng/Localizable.strings2Excel#21]
![image](https://user-images.githubusercontent.com/36063543/71577382-dc231c80-2b2e-11ea-9278-63b8bbf6e605.png)

**Comment by zqy-hisense** [comment]
同样的问题 生成的文件夹是空的

**Comment by zqy-hisense** [comment]
对excel格式有要求啊

**Comment by LuckyTruda** [comment]
同样的问题，有解决的没？

**Comment by zmctinas** [comment]
应该是路径的问题 -f 的路径到 en.lproj所在的文件夹就行 然后改文件夹不能有其他类型的文件

**Comment by JLCoderLife** [comment]
@zmctinas  大佬，我试了下路径到 en.lproj所在的文件夹，但是还是为空，后面的-t 路径有啥要求没

**Comment by zmctinas** [comment]
> @zmctinas 大佬，我试了下路径到en.lproj位于的文件夹，但是还是为空，后面的-t路径有啥要求没

你把Localizable.strings复制到他给的example/iOS/en.lproj/下 然后用他给的代码试试

**Comment by CatchZeng** [comment]
不好意思，最近事情有点多，没看到问题，能发下不能执行成功的文件吗？我试下是什么问题。

**Comment by CatchZeng** [comment]
鉴于没有进一步反馈，暂时先 close，还有问题的话可以再反馈。
也可以自行检查下，看下与 https://github.com/CatchZeng/Localizable.strings2Excel/tree/master/examples 生成出来的 Excel 文件格式是否不同
