### ISSUE TITLE
生成出来的文件是空的

### ISSUE THREAD

**Issue by JLCoderLife** [CatchZeng/Localizable.strings2Excel#22]

**Comment by CatchZeng** [comment]
能提供下翻译文件吗？

**Comment by CatchZeng** [comment]
鉴于没有反馈，暂时先 close，还有问题的话可以再反馈。
也可以自行检查下，看下与 https://github.com/CatchZeng/Localizable.strings2Excel/tree/master/examples 生成出来的 Excel 文件格式是否不同
