### ISSUE TITLE
注释和空行保留

### ISSUE THREAD

**Issue by harman-JoeyLi** [CatchZeng/Localizable.strings2Excel#3]
Hi, Catch,有两个需求这个代码暂时无法满足
1.如果.strings只有英文，其他语言没有，就会导致错乱，我想让其他语言没有的话，都用英文替代。
2.我想保留翻译和空行，使.string的行数可以和excel相对应。
看你有没有办法。

**Comment by CatchZeng** [comment]
多谢你的建议，我会尽快加入

**Comment by harman-JoeyLi** [comment]
谢了。但是看代码似乎没有显示如何解析出注释和空行的代码，不知道好做不。

**Comment by linguinan** [comment]
新添加的XlsMatch2Strings.py实现了xls导出时，保留了strings中的注释和空行，看看是否和你的需求一致@harman-JoeyLi

**Comment by CatchZeng** [comment]
@linguinan 👍
