### ISSUE TITLE
feature request：support python 3.x

### ISSUE THREAD

**Issue by jessemoe** [CatchZeng/Localizable.strings2Excel#32]

**Comment by YunFengChe** [comment]
I also want to know.

**Comment by jessemoe** [comment]
https://game.lingwoyun.cn/wechat#/recom-down?share_code=D2772864&head_img=https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epCYRSFNDLEs9RiaxxgSSbn8yXUVSgmF8iczNP6QK6IvFOprQpAkTiboT2Yl86waTrXia7GMnicUZ7G6JQ/132&nickName=blur
