### ISSUE TITLE
win10下面android转换不成功

### ISSUE THREAD

**Issue by linuxhsj** [CatchZeng/Localizable.strings2Excel#9]
感谢大神作品，不过我运行不成功。
1、步骤：
按照说明一步步来，cmd告诉我“Convert successfully! you can see xls file in xls/Localizable.xls”。但是我打开Localizable.xls文件发现是空的。
2、截图
运行截图如下http://note.youdao.com/noteshare?id=9cc80867b6e3538be831cc54f40e4439

**Comment by linuxhsj** [comment]
@CatchZeng

**Comment by CatchZeng** [comment]
不好意思，最近比较忙，现在才看到，晚上我回去用win10测试下。

**Comment by linuxhsj** [comment]
win10现在可以用了、非常感谢  @CatchZeng

**Comment by CatchZeng** [comment]
客气
